name: CI PR Test
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    name: Run PR title check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node-nvm

      - name: Validate Title of PR
        run: node .github/scripts/checkPrTitle.js "${{ github.event.pull_request.title }}"

  lint-build-test:
    name: Lint Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-nvm

      - name: Install dependencies
        run: npm ci

      - name: Lint All apps and libs
        run: npx nx run-many -t lint build test --all


  e2e-test:
    name: e2e-test
    if: ${{ github.event.pull_request.draft == false }}
    needs: [ lint-build-test ]
    runs-on: ubuntu-latest
    services:
      #      elasticsearch:
      #        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
      #        options:
      #          --health-cmd "curl http://localhost:9200/_cluster/health"
      #          --health-interval 10s
      #          --health-timeout 30s
      #          --health-retries 10
      #          -e "discovery.type=single-node"
      #          -e "xpack.security.enabled=false"
      #        ports:
      #          - 9200:9200
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - db_vol:/data/db
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node-nvm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers and dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: DEBUG=pw:webserver npx nx run e2e:e2e

      - name: Upload playwright html report to Artifacts
        uses: actions/upload-artifact@v6
        if: failure() || success()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

  publish-playwright-report:
    name: Publish playwright report
    needs: [ e2e-test ]
    if: ${{ (needs.e2e-test.result != 'skipped') && (failure() || success()) }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress:
        false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-nvm
      - name: Down playwright html report from Artifacts
        uses: actions/download-artifact@v7
        with:
          name: playwright-report
          path: playwright-report
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'playwright-report'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Populate playwright report to summary
        run: |
          echo "# Deployed playwright report to ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY

  status_check:
    runs-on: ubuntu-latest
    needs:
      - check_pr_title
      - lint-build-test
      - e2e-test
      - publish-playwright-report
    if: ${{ always() }}
    name: Check all jobs' statuses to be success
    steps:
      - run: echo "All jobs passed successfully."
        if: |
          ${{ needs.check_pr_title.result == 'success' &&
          needs.lint-build-test.result == 'success' &&
          needs.e2e-test.result == 'success' &&
          needs.publish-playwright-report.result == 'success' }}

      - run: process.exit(1)
        if: |
          ${{
          !(needs.check_pr_title.result == 'success' &&
          needs.lint-build-test.result == 'success' &&
          needs.e2e-test.result == 'success' &&
          needs.publish-playwright-report.result == 'success') }}

#
#      - name: Upload playwright blob report to Artifacts
#        uses: actions/upload-artifact@v6
#        if: always()
#        with:
#          name: blob-report
#          path: blob-report
#          retention-days: 30
#
#      - name: Upload nyc report row data to Artifacts
#        uses: actions/upload-artifact@v6
#        if: always()
#        with:
#          name: e2e_nyc_output
#          path: e2e_nyc_output
#          retention-days: 30
#
#      - name: Upload current run allure result to Artifacts
#        uses: actions/upload-artifact@v6
#        if: always()
#        with:
#          name: allure-results
#          path: allure-results
#          retention-days: 30
#
#      - name: Upload error log to Artifacts
#        uses: actions/upload-artifact@v6
#        if: always()
#        with:
#          name: error.log
#          path: error.log
#          retention-days: 30
#
#  publish-playwright-coverage-html-report:
#    name: Publish playwright coverage report
#    needs: [ e2e-test ]
#    if: always()
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - name: Azure Login
#        uses: azure/login@v2
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: generate playwright coverage report
#        uses: ./.github/actions/generate-playwright-coverage-report
#
#      - name: Upload playwright coverage report to Azure
#        if: always()
#        uses: azure/cli@v2
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az storage blob upload-batch --account-name mysimplewebsite -s ./coverage-e2e -d playwright-coverage --destination-path ${{github.event.pull_request.number}} --overwrite
#
#      - name: Populate coverage report to job summary
#        if: always()
#        run: |
#          echo "# Deployed playwright coverage report to https://mysimplewebsite.blob.core.windows.net/playwright-coverage/${{github.event.pull_request.number}}/lcov-report/index.html" >> $GITHUB_STEP_SUMMARY
#
#  publish-allure-report:
#    name: Publish allure report
#    needs: [ e2e-test ]
#    if: always()
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - run: npm ci
#
#      - name: Setup JDK
#        uses: actions/setup-java@v4.2.1
#        with:
#          distribution: 'microsoft'
#          java-version: '21'
#
#      - name: Azure Login
#        uses: Azure/login@v2
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: generate allure report
#        uses: ./.github/actions/generate-allure-report
#
#      - name: Upload allure report to Azure
#        uses: azure/cli@v2
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az storage blob upload-batch --account-name mysimplewebsite -s ./allure-report -d allure-report --overwrite
#
#      - name: Populate allure report to job summary
#        shell: bash
#        run: |
#          echo "# Deployed allure report to https://mysimplewebsite.blob.core.windows.net/allure-report/index.html" >> $GITHUB_STEP_SUMMARY
